apiVersion: apps/v1
kind: Deployment
metadata:
 name: sample-python
 labels:
   app: sample-python
spec:
 selector:
  matchLabels:
   app: sample-python
 template:
  metadata:
   labels:
    app: sample-python
  spec:
   containers:
   - image: 018556395605.dkr.ecr.ap-northeast-1.amazonaws.com/python-app:latest
     name: python-flask
     imagePullPolicy: Always
     ports:
     - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: sample-python
spec:
    ports:
    - name: “sample-python”
      targetPort: 80
      port: 5000
      nodePort: 30275
      protocol: TCP
    selector:
      app: sample-python
    type: NodePort
